### ISSUE TITLE
Can't launch on armhf/armv7l 

### ISSUE THREAD

**Issue by ghost** [stevedesmond-ca/vscode-arm#5]
I just ran "code" and it doesn't launches.Any help?

**Comment by SteveDesmond-ca** [comment]
If you run it with `--debug` or `--verbose` or `--wait` it should output to `STDOUT`/`STDERR` -- can you let me know what it fails with?

**Comment by ghost** [comment]
I did and a few files were unlinked.I fixed it and the keyboard issue.
